version: '3'

includes:
  env:
    taskfile: ./taskfiles/env/Taskfile_{{OS}}.yml
    optional: true

tasks:
  init:
    cmds:
      - task: env:init
  init:py:
    cmds:
      - task: env:init:py

  lint:
    cmds:
      - autopep8 . --in-place --recursive
