version: '3'

includes:
  env:
    taskfile: ./taskfiles/env/Taskfile_{{OS}}.yml
    optional: true

tasks:
  init:
    cmds:
      - task: env:init
  init:py:
    cmds:
      - task: env:init:py

  lint:
    cmds:
      - flake8 --ignore E501,E203
  lint:fix:
    cmds:
      - black --line-length 99999 .

  test:
    cmds:
      - pytest .

  test:cover:
    cmds:
      - |
        coverage run -m pytest
        coverage report -m
        coverage html -d coverage_report
  test:clean:
    cmds:
      - rm -rf coverage_report .coverage
