version: '3'

includes:
  env:
    taskfile: ./taskfiles/env/Taskfile_{{OS}}.yml
    optional: true

tasks:
  init:
    cmds:
      - task: env:init
  init:py:
    cmds:
      - task: env:init:py

  lint:
    cmds:
      - flake8 --ignore E501
  lint:fix:
    cmds:
      - autopep8 --ignore=E501 . --in-place --recursive

  test:
    cmds:
      - pytest .
